sequenceDiagram
    %% Peserta sequence diagram
    title Diagram Urutan - Peserta
    autonumber
    participant Peserta as Peserta
    participant HalamanLogin as Halaman Login
    participant HalamanProfile as Profil
    participant HalamanPelatihan as Pelatihan

    Peserta ->> HalamanLogin: Login ke sistem
    HalamanLogin ->> HalamanLogin: Autentikasi berhasil
    HalamanLogin ->> Peserta: Konfirmasi login
    Peserta ->> HalamanProfile: Buka profil
    HalamanProfile ->> Peserta: Tampilkan data profil
    Peserta ->> HalamanPelatihan: Buka pelatihan
    HalamanPelatihan ->> Peserta: Tampilkan daftar pelatihan
    Peserta ->> HalamanLogin: Logout
